### ISSUE TITLE
Get 500 error if i run program

### ISSUE THREAD

**Issue by vampywiz17** [imrabti/tvshowtime-plex#27]
I get this error if i run this program:

15:17 INFO  - Starting ApplicationLauncher v1.0.3-RELEASE on Ubuntu with PID 8855 (/home/vamp/download/tvshowtime-plex-1.0.3/tvshowtimeplex.jar started by vamp in /home/vamp/download/tvshowtime-plex-1.0.3/config)
15:17 INFO  - No active profile set, falling back to default profiles: default
15:17 INFO  - Started ApplicationLauncher in 3.384 seconds (JVM running for 4.105)
15:17 INFO  - Linking with your TVShowTime account using the code b***************************
15:17 INFO  - Please open the URL https://www.tvshowtime.com/activate in your browser
15:17 INFO  - Connect with your TVShowTime account and type in the following code :
15:17 INFO  - 50d8-9f0a
15:17 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
15:17 INFO  - AccessToken from TVShowTime with success : AccessToken{access_token='3*********************'}
15:17 INFO  - AccessToken store successfully inside a file...
15:17 INFO  - Calling Plex with a X-Plex-Token...
15:17 INFO  - Mark Black-ish - S1E22 as watched in TVShowTime
15:17 INFO  - Mark Supergirl - S2E2 as watched in TVShowTime
Exception in thread "Timer-0" org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:641)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:597)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:475)
        at org.nuvola.tvshowtime.ApplicationLauncher.markEpisodeAsWatched(ApplicationLauncher.java:250)
        at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:232)
        at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:178)
        at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:63)
        at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:140)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

it mark "watched" on TVShowtime, but get this thing after i run the program

**Comment by imrabti** [comment]
Hello, I have released a new version 1.0.5 (I see you are using 1.0.3), It may fix your problem, and also I have updated the documentation. 

Check the README now the property **nuvola.pms.token** is required, and you need to provide a token to be able to communicate with your PMS. I explain in the README how to grab Token from your PMS.

**Comment by vampywiz17** [comment]
Yes, i use it now :) I try the 1.0.5 but i affect a other prob.

2016-10-30 18:45:03.923  INFO 4392 --- [main] o.nuvola.tvshowtime.ApplicationLauncher  : Starting ApplicationLauncher v1.0.5-RELEASE on ubuntu with PID 4392 (/home/vamp/tvshowtimeplex/tvshowtime-$
2016-10-30 18:45:03.951  INFO 4392 --- [main] o.nuvola.tvshowtime.ApplicationLauncher  : No active profile set, falling back to default profiles: default
2016-10-30 18:45:07.000  INFO 4392 --- [main] o.nuvola.tvshowtime.ApplicationLauncher  : Started ApplicationLauncher in 4.317 seconds (JVM running for 5.287)
2016-10-30 18:45:07.041  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : AccessToken loaded from file with success : AccessToken{access_token='3beb62678bc70eea88725c747$
2016-10-30 18:45:07.062  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : Calling Plex with a X-Plex-Token...
2016-10-30 18:45:08.181  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : Mark Supergirl - S2E3 as watched in TVShowTime
2016-10-30 18:45:08.386  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : Mark Agymenők - S10E6 as watched in TVShowTime
2016-10-30 18:45:08.540  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : Mark Supergirl - S2E2 as watched in TVShowTime
2016-10-30 18:45:08.700  INFO 4392 --- [pool-1-thread-1] o.nuvola.tvshowtime.ApplicationLauncher  : Mark Westworld - S1E3 as watched in TVShowTime

i create a cron to start the .jar file every hour. but it is not closed automatically and every hour it start a new java process....

**Comment by vampywiz17** [comment]
Well, now i use it here:

0 \* \* \* \* java -jar /home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.5/tvshowtimeplex.jar

1 \* \* \* \* pkill -f 'java -jar'

**Comment by Lulu300** [comment]
I'm on the last version and when i run the program i've got this error : 
pi@raspberrypi:~/tvshowtime-plex-1.0.5 $ java -jar tvshowtimeplex.jar
 _____     _____ _                 _____ _                      ______ _
|_   _|   /  ___| |               |_   _(_)                     | ___ \ |
  | |_   _\ `--.| |__   _____      _| |  _ _ __ ___   ___ ______| |_/ / | _____  __
  | \ \ / /`--. \ '_ \ / _ \ \ /\ / / | | | '_ ` _ \ / _ \______|  __/| |/ _ \ \/ /
  | |\ V //\__/ / | | | (_) \ V  V /| | | | | | | | |  __/      | |   | |  __/>  <
  \_/ \_/ \____/|_| |_|\___/ \_/\_/ \_/ |_|_| |_| |_|\___|      \_|   |_|\___/_/\_\

   :::  TVShowTime-Plex (V1.0.5)  :::


16:05 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on raspberrypi with PID 18716 (/home/pi/tvshowtime-plex-1.0.5/tvshowtimeplex.jar started by pi in /home/pi/tvshowtime-plex-1.0.5)
16:05 INFO  - No active profile set, falling back to default profiles: default
16:05 INFO  - Started ApplicationLauncher in 8.573 seconds (JVM running for 10.321)
16:05 INFO  - AccessToken loaded from file with success : AccessToken{access_token='0ca2912e5734121ddc4ee5b86cc8cc1c'}
16:05 INFO  - Calling Plex with a X-Plex-Token...
16:05 ERROR - Error during marking episodes as watched.
16:05 ERROR - 500 Internal Server Error
pi@raspberrypi:~/tvshowtime-plex-1.0.5 $

**Comment by imrabti** [comment]
Hello, can you please specify which version of Plex Media Server are you using ?
Did you provide the Plex Token as described in the Readme ?

**Comment by Lulu300** [comment]
Hello, i use version 1.3.3.3148 of Plex Media Server and yes I provide the plex Token.

**Comment by iXo** [comment]
Hi, new user here, I tryied to sync all my show (markall=true), and found that a 500 error seems to be fired by the plex server after 15 * 10 loop of valid show marked as seen.

Here is the stack trace (I have added a .printStrackTrace()) : 

> 21:45 ERROR - Error during marking episodes as watched.
21:45 ERROR - 500 Internal Server Error
org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:700)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:653)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:613)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:531)
	at org.nuvola.tvshowtime.ApplicationLauncher.markEpisodeAsWatched(ApplicationLauncher.java:290)
	at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:266)
	at org.nuvola.tvshowtime.ApplicationLauncher.init(ApplicationLauncher.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Don't pay attention to the lines number, as I have forgot that I set up eclipse to perform format on save, and as I don't like { on the end of the line, everything is messed up.

The error markEpisodeAsWatched(ApplicationLauncher.java:290) is involving this line of code :

`ResponseEntity<Message> content = tvShowTimeTemplate.exchange(checkinUrl, POST, entity, Message.class);`


I am using Plex pass server #1.7.5.4035 and tvshowtime-plex 1.0.6 from git clone.
Oracle Java 1.8.0_74 on OSX, and OpenJDK 1.8.0_131 on Alpine linux.

**Comment by SkYNewZ** [comment]
Any news about this issue ?
https://pastebin.com/cwdcpjB9

* v1.0.6
* `OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-2~deb9u1-b13)`

**Comment by jrcalvert** [comment]
I am experiencing this also when config is set to mark all episodes (v1.0.6)
  14:02 ERROR - Error during marking episodes as watched.
  14:02 ERROR - 500 Internal Server Error
I have tried OpenJDK 8 and Oracle JDK 8
