### ISSUE TITLE
Error 401 Unauthorised

### ISSUE THREAD

**Issue by balazsnyitray-seon** [imrabti/tvshowtime-plex#35]
Hi, i tried to run the jar, the first time it seemed to be ok (i give the tvshowtime webpage the needed code, it run for some time, then the ssh panel seemed to be done or freezed or smg, after a few lines it stopped working.

Then i closed ssh, tried to run the jar and get this error:
10:52 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on NyitrayNAS with PID 21013 (/volume1/homes/balazs.nyitray/2/tvshowtimeplex.jar started by root in /root)
10:52 INFO  - No active profile set, falling back to default profiles: default
10:52 INFO  - Started ApplicationLauncher in 5.499 seconds (JVM running for 6.648)
10:52 INFO  - AccessToken loaded from file with success : AccessToken{access_token='2f949b6ec2206069ac37f1cba522476e'}
10:52 ERROR - Error during marking episodes as watched.
10:52 ERROR - 401 Unauthorized

What is unauthorised? the x-plex code seems to be ok, tvshowtime get the acces in the first time. however i cannot manage to restart the whole prosecc, i deleted the jar and uploaded froms scratch but i cannot get the thshowtime access code, only this 401 error. 
What to do? thx!

**Comment by balazsnyitray-seon** [comment]
Ok, i found the file that needed to be deleted.
I run the jar from scratch and this is the problem:
11:11 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
11:11 INFO  - AccessToken from TVShowTime with success : AccessToken{access_token='2f949b6ec2206069ac37f1cba522476e'}
11:11 INFO  - AccessToken store successfully inside a file...
Exception in thread "Timer-0" org.springframework.web.client.HttpClientErrorException: 401 Unauthorized
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:312)
	at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:214)
	at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:175)
	at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:64)
	at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:137)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

**Comment by balazsnyitray-seon** [comment]
BTW im running plex and the jar on the same synology nas.
Maybe the problem is with the x-plex token? or the localhost, which i didnt change? tried with specific ip address, doesnt help:S

**Comment by imrabti** [comment]
The issue comes from the call to Plex Server web service, it appears the the X-Plex-Token is not correctly configured.

**Comment by imrabti** [comment]
You need to configure that in the file application.properties that is inside the config folder.

**Comment by balazsnyitray-seon** [comment]
I already did, but probably i made syntax error?
I did like this:
nuvola.pms.token = mylongunreadabletoken

I think i found my token correctly, following the links you provided (video info - xml, copy from url the part after xcode...

well, maybe i will change my pw and generate that way a new token. Thx for the info!

**Comment by rowyroald** [comment]
Hi,

I have the same problem/error (401 Unauthorized) as @balazsnyitray .
I also try to get it working on my Synology and only added the X-Plex-Token to the application.properties file, left the rest as default.
@imrabti : Could you please let me know if you have a solution for this?
