### ISSUE TITLE
NullPointerException on running

### ISSUE THREAD

**Issue by extrajulius** [imrabti/tvshowtime-plex#39]
![image](https://user-images.githubusercontent.com/5784581/31305552-290c27ba-ab45-11e7-9200-ce7cdfc0e7b5.png)

Getting this error each time when trying to run the script. I use Ubuntu server 17.04, local Plex Media Server forwarded through ufw and router. Using openjdk-8-jre package.

**Comment by baggott** [comment]
I have same error here, using windows 10 and java 8 update 144 (build 1.8.0_144-b01).

21:56 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on DESKTOP-QTBI71K with PID 11988 (C:\tvshowtime-plex-1.0.5\tvshowtimeplex.jar started by alexa in C:\tvshowtime-plex-1.0.5)
21:56 INFO  - No active profile set, falling back to default profiles: default
21:56 INFO  - Started ApplicationLauncher in 3.581 seconds (JVM running for 5.976)
21:56 INFO  - Linking with your TVShowTime account using the code Ag378a5Y_Vphtyi0hs4f
21:56 INFO  - Please open the URL https://www.tvtime.com/activate in your browser
21:56 INFO  - Connect with your TVShowTime account and type in the following code :
21:56 INFO  - 9999-9999 _(I change this here)_
21:56 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
21:58 INFO  - AccessToken from TVShowTime with success : AccessToken{access_token='622e079a2ea603d86d8cca5861b445fc'}
21:58 INFO  - AccessToken store successfully inside a file...
21:58 INFO  - Calling Plex with a X-Plex-Token...
21:58 INFO  - Mark This Is Us - S2E2 as watched in TVShowTime
**Exception in thread "Timer-0" org.springframework.web.client.HttpServerErrorException: 500 Internal Server Error**
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:667)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:620)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580)
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:498)
        at org.nuvola.tvshowtime.ApplicationLauncher.markEpisodeAsWatched(ApplicationLauncher.java:251)
        at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:229)
        at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:175)
        at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:64)
        at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:137)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)

**Comment by baggott** [comment]
I start the program again and receive this error:

C:\tvshowtime-plex-1.0.5>java -jar tvshowtimeplex.jar
 _____     _____ _                 _____ _                      ______ _
|_   _|   /  ___| |               |_   _(_)                     | ___ \ |
  | |_   _\ `--.| |__   _____      _| |  _ _ __ ___   ___ ______| |_/ / | _____  __
  | \ \ / /`--. \ '_ \ / _ \ \ /\ / / | | | '_ ` _ \ / _ \______|  __/| |/ _ \ \/ /
  | |\ V //\__/ / | | | (_) \ V  V /| | | | | | | | |  __/      | |   | |  __/>  <
  \_/ \_/ \____/|_| |_|\___/ \_/\_/ \_/ |_|_| |_| |_|\___|      \_|   |_|\___/_/\_\

   :::  TVShowTime-Plex (V1.0.5)  :::


22:06 INFO  - Starting ApplicationLauncher v1.0.5-RELEASE on DESKTOP-QTBI71K with PID 12648 (C:\tvshowtime-plex-1.0.5\tvshowtimeplex.jar started by alexa in C:\tvshowtime-plex-1.0.5)
22:06 INFO  - No active profile set, falling back to default profiles: default
22:06 INFO  - Started ApplicationLauncher in 2.57 seconds (JVM running for 3.067)
22:06 INFO  - AccessToken loaded from file with success : AccessToken{access_token='622e079a2ea603d86d8cca5861b445fc'}
22:06 INFO  - Calling Plex with a X-Plex-Token...
22:06 INFO  - Mark This Is Us - S2E2 as watched in TVShowTime
22:06 ERROR - Error during marking episodes as watched.
22:06 ERROR - 500 Internal Server Error
