### ISSUE TITLE
TVshowtime-plex not working on latest Ubuntu version (18.04)

### ISSUE THREAD

**Issue by vampywiz17** [imrabti/tvshowtime-plex#41]
Hello there,

Today i update the latest Ubuntu version, but tvshowtime-plex not working in this version.

I get this:

```

   :::  TVShowTime-Plex (V1.0.5)  :::


00:35 INFO  - Starting ApplicationLauncher v1.0.6-RELEASE on ubuntu with PID 11179 (/home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.6/tvshowtimeplex.jar started by root in /root)
00:35 INFO  - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.6/tvshowtimeplex.jar!/BOOT-INF/lib/spring-core-4.3.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
00:35 INFO  - Started ApplicationLauncher in 3.86 seconds (JVM running for 4.9)
00:35 INFO  - AccessToken loaded from file with success : AccessToken{access_token='3beb62678bc70eea88725c7474428e2e'}
00:35 INFO  - Calling Plex with a X-Plex-Token...
00:35 ERROR - Error during marking episodes as watched.
00:35 ERROR - null

```

If i try to generate a new token:

```
   :::  TVShowTime-Plex (V1.0.5)  :::


00:33 INFO  - Starting ApplicationLauncher v1.0.6-RELEASE on ubuntu with PID 11131 (/home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.6/tvshowtimeplex.jar started by root in /root)
00:33 INFO  - No active profile set, falling back to default profiles: default
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/home/vamp/tvshowtimeplex/tvshowtime-plex-1.0.6/tvshowtimeplex.jar!/BOOT-INF/lib/spring-core-4.3.8.RELEASE.jar!/) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
00:33 INFO  - Started ApplicationLauncher in 3.961 seconds (JVM running for 4.923)
00:33 INFO  - Linking with your TVShowTime account using the code XOoXO1xmjecGbqnV_Rkf
00:33 INFO  - Please open the URL https://www.tvtime.com/activate in your browser
00:33 INFO  - Connect with your TVShowTime account and type in the following code :
00:33 INFO  - b7e9-7e4f
00:33 INFO  - Waiting for you to type in the code in TVShowTime :-D ...
00:33 INFO  - AccessToken from TVShowTime with success : AccessToken{access_token='3beb62678bc70eea88725c7474428e2e'}
00:33 INFO  - AccessToken store successfully inside a file...
00:33 INFO  - Calling Plex with a X-Plex-Token...
Exception in thread "Timer-0" java.lang.NullPointerException
        at org.nuvola.tvshowtime.ApplicationLauncher.processWatchedEpisodes(ApplicationLauncher.java:220)
        at org.nuvola.tvshowtime.ApplicationLauncher.loadAccessToken(ApplicationLauncher.java:178)
        at org.nuvola.tvshowtime.ApplicationLauncher.access$000(ApplicationLauncher.java:67)
        at org.nuvola.tvshowtime.ApplicationLauncher$1.run(ApplicationLauncher.java:140)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)

```

**Comment by vampywiz17** [comment]
OK, i delete OpenJDK and install latest Oracle Java 8 and it working again!
